### ISSUE TITLE
Wifi adapter Not showing

### ISSUE THREAD

**Issue by ramjirau** [sharathc213/wifi_deauth_detector#1]
my TP-Link AC600 Wifi adapter not detecting on the application.

**Comment by sharathc213** [comment]
> my TP-Link AC600 Wifi adapter not detecting on the application.

please install the driver for the adapter.
https://github.com/nlkguy/archer-t2u-plus-linux.git(Please check the Link)

**Comment by ramjirau** [comment]
Thanku
